name: Deploy to GitHub Pages
on:
  workflow_dispatch:
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.1.0
          with:
            branch: main
